### ISSUE TITLE
Firebase config file shouldn't be in the repository

### ISSUE THREAD

**Issue by lablnet** [BlackArcX/classx_vue#9]
The firebase confidential detail in git may cause security issue, like for instance anyone can use it and destroy your database and perform operation.

ref: https://github.com/BlackArcX/classx_vue/blob/master/src/firebase.js#L5

I think it can be better if you consider the following approach
`firebaseConfig.js`
```js
const firebaseConfig = {
  apiKey: '',
  authDomain: '',
  databaseURL: '',
  projectId: '',
  storageBucket: '',
  messagingSenderId: '',
  appId: '',
  measurementId: '',
};
export default firebaseConfig
```
And in your firebase file
``` import firebaseConfig from "firebaseConfig"```
and you have to add `.gitignore` in `src` folder
or may be any similar to this if you have in mind.

Thanks

**Comment by nmanumr** [comment]
That's a good be debate question. And I have the following arguments in defense.

1. When the application is compiled these configurations will be still available publically. So, these configurations should be designed to be made public.
2. If we remove these configurations from the repo, instead of solving anything particular, we will be creating a hell for contributors who want to test the application locally.

It's just my own opinion and if you have a different opinion I would love to hear that too.

> The firebase confidential detail in git may cause security issues, like for instance anyone can use it and destroy your database and perform an operation.

As far as this issue is concerned firebase provides [firestore security rules](https://firebase.google.com/docs/firestore/security/overview) for this purpose. We had implemented those rules too to avoid any unauthorized destructive action.

**Comment by lablnet** [comment]
> That's a good be debate question. And I have the following arguments in defense.
> 
> As far as this issue is concerned firebase provides [firestore security rules](https://firebase.google.com/docs/firestore/security/overview) for this purpose. We had implemented those rules too to avoid any unauthorized destructive action.

Your argument seems right to me, and the reference link about firebase security.
So issue is should be.
